export const FETCH_MOVIES = "FETCH_MOVIES";
export const FETCH_MOVIES_INITIAL = "FETCH_MOVIES_INITIAL";
export const FETCH_MOVIES_LOADING = "FETCH_MOVIES_LOADING";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_FAILURE = "FETCH_MOVIES_FAILURE";

export const FETCH_MOVIE = "FETCH_MOVIE";
export const FETCH_MOVIE_INITIAL = "FETCH_MOVIE_INITIAL";
export const FETCH_MOVIE_LOADING = "FETCH_MOVIE_LOADING";
export const FETCH_MOVIE_SUCCESS = "FETCH_MOVIE_SUCCESS";
export const FETCH_MOVIE_FAILURE = "FETCH_MOVIE_FAILURE";
